version: "3"

services:
  kafka:
    image: landoop/fast-data-dev:latest
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
    environment:
#      - "ADV_HOST=127.0.0.1"
      - "ADV_HOST=kafka"

  spark-master:
    image: bde2020/spark-master:2.3.0-hadoop2.7
    container_name: spark-master
    volumes:
      - /tmp/spark:/tmp/spark
    ports:
      - 18080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:2.3.0-hadoop2.7
    container_name: spark-worker
    depends_on:
      - spark-master
    volumes:
      - /tmp/spark:/tmp/spark
    ports:
      - 18081:8081
      - 4040:4040
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
